name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binary for AMD64
        run: |
          GOOS=linux GOARCH=amd64 go build -o slack-notifier-go-linux-amd64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: slack-notifier-go-linux-amd64
          generate_release_notes: true
